framework:
    messenger:
        transports:
            applications_outbox:
                dsn: 'doctrine://default?queue_name=applications_outbox'
                options:
                    table_name: outbox_messages
                    auto_setup: false
                retry_strategy:
                    max_retries: 10
                    delay: 1000
                    multiplier: 2
                    max_delay: 10000
                failure_transport: applications_outbox_failed

            applications_outbox_failed:
                dsn: 'doctrine://default?queue_name=applications_outbox_failed'
                options:
                    table_name: failed_messages
                    auto_setup: false

            applications_verification:
                dsn: '%env(RABBITMQ_VERIFICATION_DSN)%'
                retry_strategy:
                    max_retries: 10
                    delay: 1000
                    multiplier: 2
                    max_delay: 10000
                failure_transport: applications_verification_failed

            applications_verification_failed:
                dsn: 'doctrine://default?queue_name=applications_verification_failed'
                options:
                    table_name: failed_messages
                    auto_setup: false

        routing:
            App\LoanApplication\Application\Command\CheckBorrower: applications_outbox
            App\LoanApplication\Application\Command\RelayedCheckBorrower: applications_verification
