@host = http://localhost:8080

### Create

POST {{host}}/applications
Content-Type: application/json

{
    "personalCode": "123456-78901",
    "amount": "1500.00",
    "term": 12,
    "currency": "EUR"
}


### Get by ID
GET {{host}}/applications/01a08527-894b-74df-b66f-8eaaaf6b0ae0
Content-Type: application/json

